name: scure_base
description:  minimal implementation of bech32, base64, base58, base32 & base16.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.3

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.7
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
